"""Step 2: Generate the Python source code for each planned agent."""

import re

from config import MODEL, get_llm
from planner import AgentSpec

# Every generated agent must follow this exact contract so the executor
# can run any of them the same way: JSON in on stdin, plain text out on stdout.
AGENT_TEMPLATE = '''"""{name}: {role}

Auto-generated by the Dynamic Agent Creator.
Contract: reads JSON {{"task": str, "previous_outputs": dict}} from stdin,
prints its result to stdout.
"""

import json
import os
import sys

from langchain_openai import ChatOpenAI


def run(task: str, previous_outputs: dict) -> str:
    # ... agent logic goes here ...
    ...


if __name__ == "__main__":
    payload = json.loads(sys.stdin.read())
    print(run(payload["task"], payload["previous_outputs"]))
'''

GENERATOR_PROMPT = """You are a code generator. Write ONE complete Python file for the
specialized agent described below. Output ONLY Python code, no explanations.

Agent name: {name}
Agent role: {role}
Agent instructions:
{instructions}

Hard requirements:
1. Follow this file skeleton EXACTLY (same imports, same run() signature, same __main__ block):

{template}

2. Build the LLM exactly like this (OpenRouter API):
   llm = ChatOpenAI(
       model="{model}",
       api_key=os.environ["OPENROUTER_API_KEY"],
       base_url="https://openrouter.ai/api/v1",
   )

3. Inside run(), craft a clear prompt for the LLM that:
   - states the agent's single responsibility,
   - includes the user task,
   - includes previous_outputs (results from earlier agents) when they exist.
   Call llm.invoke(prompt) and return response.content.

4. Keep the code short, readable, and self-contained. No extra features.
"""


def _strip_code_fences(text: str) -> str:
    """Remove ```python ... ``` fences if the model added them."""
    match = re.search(r"```(?:python)?\s*\n(.*?)```", text, re.DOTALL)
    return match.group(1) if match else text


def generate_agent_code(spec: AgentSpec) -> str:
    """Ask the LLM to write the Python source for one agent."""
    prompt = GENERATOR_PROMPT.format(
        name=spec.name,
        role=spec.role,
        instructions=spec.instructions,
        template=AGENT_TEMPLATE.format(name=spec.name, role=spec.role),
        model=MODEL,
    )
    response = get_llm(max_tokens=16000).invoke(prompt)
    return _strip_code_fences(response.content).strip() + "\n"
