"""Step 2: Generate the Python source for each planned agent.

The LLM writes only the agent's own logic (``run()`` plus any helpers it needs).
The surrounding runtime - imports, the OpenRouter call, the stdin/stdout
contract - comes from a fixed, trusted header defined here. That removes a
whole class of failure: the boilerplate can no longer drift, and every
generated agent is standard-library only, so it starts in ~0.05 s instead of
paying a ~6 s LangChain import.
"""

from __future__ import annotations

import re

from codeguard import check_agent_source
from config import (
    CODEGEN_ATTEMPTS,
    MAX_CHARS_PER_INPUT,
    MODEL,
    OPENROUTER_CHAT_URL,
    USAGE_MARKER,
    Usage,
    get_llm,
    response_text,
)
from planner import AgentSpec

# Placeholders filled in by _render_header(). Deliberately not str.format():
# the header contains literal braces that .format() would choke on.
_MODEL_MARKER = "@@MODEL@@"
_API_URL_MARKER = "@@API_URL@@"
_MAX_CHARS_MARKER = "@@MAX_CHARS@@"
_USAGE_MARKER_MARKER = "@@USAGE_MARKER@@"

AGENT_HEADER = '''"""Auto-generated by the Dynamic Agent Creator.

Contract: reads JSON {"task": str, "previous_outputs": dict} from stdin,
prints its result to stdout.

Standard library only, so this file runs on its own with nothing installed.
"""

import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "@@API_URL@@"
MODEL = os.environ.get("MODEL", "@@MODEL@@")
LLM_TIMEOUT_SECONDS = 120
LLM_ATTEMPTS = 3
MAX_CHARS_PER_INPUT = @@MAX_CHARS@@
USAGE_MARKER = "@@USAGE_MARKER@@"


def api_key() -> str:
    """Read the key from the environment, falling back to a nearby .env file.

    The fallback is what lets an archived agent run standalone.
    """
    key = os.environ.get("OPENROUTER_API_KEY")
    if key:
        return key
    for folder in Path(__file__).resolve().parents:
        env_file = folder / ".env"
        if not env_file.is_file():
            continue
        for line in env_file.read_text(encoding="utf-8").splitlines():
            name, separator, value = line.partition("=")
            if separator and name.strip() == "OPENROUTER_API_KEY":
                return value.strip().strip('"').strip("'")
    raise SystemExit("OPENROUTER_API_KEY is not set.")


def call_llm(prompt: str) -> str:
    """One chat completion against OpenRouter, with retries on transient errors."""
    body = json.dumps(
        {"model": MODEL, "messages": [{"role": "user", "content": prompt}]}
    ).encode("utf-8")
    request = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Authorization": "Bearer " + api_key(),
            "Content-Type": "application/json",
        },
    )

    payload = None
    last_error = None
    for attempt in range(LLM_ATTEMPTS):
        try:
            with urllib.request.urlopen(request, timeout=LLM_TIMEOUT_SECONDS) as response:
                payload = json.loads(response.read().decode("utf-8"))
            break
        except urllib.error.HTTPError as error:
            last_error = "HTTP %s %s" % (error.code, error.reason)
            if error.code < 500 and error.code != 429:
                raise SystemExit("OpenRouter returned " + last_error)
        except (urllib.error.URLError, TimeoutError, ValueError) as error:
            last_error = "%s: %s" % (type(error).__name__, error)
        if attempt < LLM_ATTEMPTS - 1:
            time.sleep(2 ** attempt)

    if payload is None:
        raise SystemExit("OpenRouter request failed: %s" % last_error)
    if "choices" not in payload:
        raise SystemExit("Unexpected OpenRouter response: %s" % json.dumps(payload)[:400])

    # Token usage goes to stderr; stdout is reserved for the result.
    print(USAGE_MARKER + " " + json.dumps(payload.get("usage") or {}), file=sys.stderr)
    return payload["choices"][0]["message"]["content"] or ""


def format_previous(previous_outputs: dict) -> str:
    """Render upstream results as labelled, length-capped sections."""
    if not previous_outputs:
        return "(none)"
    sections = []
    for name, output in previous_outputs.items():
        text = str(output)
        if len(text) > MAX_CHARS_PER_INPUT:
            text = text[:MAX_CHARS_PER_INPUT] + "\\n[...truncated...]"
        sections.append("### " + str(name) + "\\n" + text)
    return "\\n\\n".join(sections)
'''

AGENT_FOOTER = """
if __name__ == "__main__":
    payload = json.loads(sys.stdin.read())
    print(run(payload["task"], payload.get("previous_outputs") or {}))
"""

GENERATOR_PROMPT = """You are a code generator for a multi-agent system.
Write the logic for ONE specialized agent.

Agent name: {name}
Agent role: {role}
Agent instructions:
{instructions}

Write ONLY a top-level function with this exact signature, plus any small
helper functions it needs:

    def run(task: str, previous_outputs: dict) -> str:
        ...

Already defined in the module - use them, never redefine them, and do NOT
write any import statements or an "if __name__" block:
    call_llm(prompt: str) -> str          # one LLM call, returns the reply text
    format_previous(previous_outputs: dict) -> str   # labelled, capped sections

{upstream_contract}

Inside run():
- build one clear prompt that states this agent's single responsibility,
- include the user task,
- include the upstream results as described above,
- return call_llm(prompt).

Rules:
- REUSABLE: this agent is kept and run again on completely different subjects.
  Describe only its ROLE in the prompt you build. Never hardcode the current
  task's subject, topic, names, numbers or domain into a string literal - every
  one of those must come from the `task` argument at runtime.
  Write:  "You are a research agent. Gather key facts for the task below."
  Not:    "You are researching the electric scooter industry."
- Standard library only. No imports at all unless truly unavoidable.
- No file writing, no subprocess, no eval.
- Keep it short, readable and self-contained. No extra features.
- Output ONLY Python code. No explanations, no markdown fences.
"""

_FIRST_AGENT_CONTRACT = """This is the FIRST agent, so `previous_outputs` is an empty dict.
Work from the task alone and do not read any key from it."""

_UPSTREAM_CONTRACT = """`previous_outputs` is a dict whose keys are EXACTLY these upstream agent names:
{names}
Never invent a key. Read one specific result with
previous_outputs.get("<exact name>", ""), or include them all with
format_previous(previous_outputs). Reading a key that is not in the list above
silently loses that agent's work, so use the exact names. Use .get() rather than
[...]: an upstream agent that failed leaves its key absent."""

_REPAIR_PROMPT = """
The previous attempt was rejected. Fix these problems and return the corrected code:
{problems}
"""

_FENCED_BLOCK = re.compile(r"`{3}[A-Za-z0-9_+-]*[ \t]*\r?\n(.*?)`{3}", re.DOTALL)
_FENCE_LINE = "`" * 3


def _render_header() -> str:
    """Fill the trusted header's placeholders with the live configuration."""
    return (
        AGENT_HEADER.replace(_API_URL_MARKER, OPENROUTER_CHAT_URL)
        .replace(_MODEL_MARKER, MODEL)
        .replace(_MAX_CHARS_MARKER, str(MAX_CHARS_PER_INPUT))
        .replace(_USAGE_MARKER_MARKER, USAGE_MARKER)
    )


def _strip_code_fences(text: str) -> str:
    """Remove markdown fences, keeping every block the model emitted."""
    blocks = _FENCED_BLOCK.findall(text)
    if blocks:
        return "\n\n".join(block.strip("\r\n") for block in blocks)
    if _FENCE_LINE in text:
        # Unterminated fence: drop the fence lines rather than write them to a .py file.
        return "\n".join(
            line for line in text.splitlines() if not line.lstrip().startswith(_FENCE_LINE)
        )
    return text


def assemble_agent(body: str) -> str:
    """Wrap a generated ``run()`` body in the trusted runtime."""
    return f"{_render_header()}\n{body.strip()}\n{AGENT_FOOTER}"


def _upstream_contract(upstream: list[str]) -> str:
    if not upstream:
        return _FIRST_AGENT_CONTRACT
    return _UPSTREAM_CONTRACT.format(names="\n".join(f'  - "{name}"' for name in upstream))


def generate_agent_code(
    spec: AgentSpec,
    upstream: list[str] | None = None,
    feedback: str | None = None,
    usage: Usage | None = None,
) -> str:
    """Return validated, ready-to-run source for one agent.

    Regenerates up to CODEGEN_ATTEMPTS times, feeding the validator's
    complaints back to the model, so malformed code never reaches disk.
    ``feedback`` carries a runtime error from an earlier execution attempt.
    """
    prompt = GENERATOR_PROMPT.format(
        name=spec.name,
        role=spec.role,
        instructions=spec.instructions,
        upstream_contract=_upstream_contract(upstream or []),
    )
    if feedback:
        prompt += _REPAIR_PROMPT.format(problems=feedback)

    llm = get_llm(max_tokens=4000)
    problems: list[str] = []
    for _ in range(CODEGEN_ATTEMPTS):
        attempt_prompt = prompt
        if problems:
            attempt_prompt += _REPAIR_PROMPT.format(
                problems="\n".join(f"- {problem}" for problem in problems)
            )

        response = llm.invoke(attempt_prompt)
        if usage is not None:
            usage.record(response)
        body = _strip_code_fences(response_text(response)).strip()
        source = assemble_agent(body)
        problems = check_agent_source(source)
        if not problems:
            return source

    raise ValueError(
        f"could not generate valid code for {spec.name!r} after {CODEGEN_ATTEMPTS} attempts: "
        + "; ".join(problems)
    )
