"""Tests for the answers AgentGod gives about itself.

These exist because the old answers were generated by agents that knew
nothing about this project, and confidently advertised live data retrieval
and dataset analysis - two things it specifically cannot do. Everything here
is about honesty: the numbers must be read, and the limits must be present.
"""

from __future__ import annotations

import identity
from identity import (
    LIMITS,
    SKILLS,
    Snapshot,
    describe_capabilities,
    describe_greeting,
    describe_identity,
    snapshot,
)

SAMPLE = Snapshot(
    model="claude-sonnet-5",
    max_agents=4,
    timeout_seconds=300,
    library=(("research_agent", "gather facts", 7),),
    runs=12,
)


def test_the_capability_answer_states_the_real_configuration():
    text = describe_capabilities(SAMPLE)
    assert "claude-sonnet-5" in text
    assert "4 agents per task" in text
    assert "1 agent kept" in text
    assert "12 runs archived" in text


def test_the_capability_answer_lists_the_limits_not_just_the_strengths():
    """Search is not browsing, and the difference is the one people assume away."""
    text = describe_capabilities(SAMPLE).lower()
    assert "cannot" in text
    assert "no browsing" in text
    assert "no images" in text or "text in, text out" in text


def test_the_capability_answer_never_claims_a_capability_it_lacks():
    text = describe_capabilities(SAMPLE).lower()
    for false_promise in ("real-time", "browse the web", "run your code"):
        # Any mention must be a denial, not an offer.
        if false_promise in text:
            assert "no " in text or "cannot" in text


def test_every_advertised_skill_appears_in_the_answer():
    text = describe_capabilities(SAMPLE)
    for title, _detail in SKILLS:
        assert title in text


def test_every_limit_appears_in_the_answer():
    text = describe_capabilities(SAMPLE)
    for limit in LIMITS:
        assert limit.split(".")[0] in text


def test_the_identity_answer_describes_this_program_not_a_generic_assistant():
    text = describe_identity(SAMPLE)
    assert "AgentGod" in text
    assert "claude-sonnet-5" in text
    assert "research_agent" in text
    # the pipeline, which is the actual answer to "how do you work"
    for phase in ("plan", "forge", "run", "merge"):
        assert phase in text


def test_the_identity_answer_survives_an_empty_library():
    text = describe_identity(Snapshot(model="m", max_agents=2, timeout_seconds=1))
    assert "AgentGod" in text
    assert "first task" in text


def test_the_greeting_tells_the_user_what_to_type_next():
    text = describe_greeting(SAMPLE)
    assert "AgentGod" in text
    assert "/help" in text
    assert "quit" in text


# --- the live read -------------------------------------------------------------


def test_snapshot_reads_the_configuration():
    from config import MAX_AGENTS, MODEL

    state = snapshot()
    assert state.model == MODEL
    assert state.max_agents == MAX_AGENTS


def test_snapshot_survives_an_unreadable_library(monkeypatch):
    """A question about the system must still get an answer on a broken install."""
    import library

    def explode():
        raise OSError("disk gone")

    monkeypatch.setattr(library, "catalogue", explode)
    state = snapshot()
    assert state.library == ()
    assert describe_capabilities(state)


def test_the_status_line_pluralises_honestly():
    one = Snapshot(model="m", max_agents=1, timeout_seconds=1, library=(("a", "b", 0),), runs=1)
    assert "1 agent kept" in one.status_line()
    assert "1 run archived" in one.status_line()

    none = Snapshot(model="m", max_agents=1, timeout_seconds=1)
    assert "0 agents kept" in none.status_line()
    assert "0 runs archived" in none.status_line()


def test_skills_and_limits_are_not_empty():
    """A capability answer with nothing in it is worse than none."""
    assert identity.SKILLS
    assert identity.LIMITS
